import Head from 'next/head'
import Nav from "@/components/nav"
import { useEffect, useState } from 'react'

export default function Dashboard({ tokenExpired }: any){
  const [user, setUser] = useState('')

  useEffect(() => {
    const userStr: any = window.localStorage.getItem('lithium_user')
    const sessionUser = JSON.parse(userStr)
    const firstName = sessionUser.user.firstName
    const lastName = sessionUser.user.lastName
    setUser(firstName + ' ' + lastName)
  }, [])
  return(
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <Nav tokenExpired={tokenExpired}/>

      <div className='flex justify-center mt-10 text-3xl text-gray-700 font-mono'>
        <h1>{`Hey ${user}!`}</h1>
      </div>
    </div>
  )
}

export async function getServerSideProps(context: any) {
  const userStr = context.req.cookies['lithium_user']

  if(userStr){
    const userLithium = JSON.parse(userStr)
    const now = new Date()

    if(now.getTime() > userLithium.expiry){
      // token is expired
      return {
        redirect: {
          permanent: false,
          destination: `/signin?redirect=${context.req.url}`
        },
      };
    }else{
      // user is still logged in
      return{
        props: {
          tokenExpired: false
        }
      }
    }
  }else{
    return {
      redirect: {
        permanent: false,
        destination: `/signin?redirect=${context.req.url}`
      },
    };
  }
}