import Head from 'next/head'
import Nav from '@/components/nav'

export default function Home({ tokenExpired }) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div>
        <Nav tokenExpired={tokenExpired}/>

        <div className='flex justify-center mt-10 text-3xl text-gray-700 font-mono'>
          <h1>Hello Welcome to Lithium Home Page</h1>
        </div>
      </div>
    </>
  )
}

export async function getServerSideProps(context: any) {
  const userStr = context.req.cookies['lithium_user']

  if(userStr){
    const userEden = JSON.parse(userStr)
    const now = new Date()

    if(now.getTime() > userEden.expiry){
      // token is expired
      return {
        props: { 
          tokenExpired: true
        } 
      }
    }else{
      // user is still logged in
      return{
        props: { 
          tokenExpired: false
        }
      }
    }
  }else{
    return{
      props: {
        tokenExpired: true
      }
    }
  }
}